DROP DATABASE IF EXISTS EXAMENSEGURIDAD;
CREATE DATABASE EXAMENSEGURIDAD;
USE EXAMENSEGURIDAD;
CREATE TABLE USUARIO(
	id_user int primary key AUTO_INCREMENT,
	nombre VARCHAR(100) NOT NULL,
	password VARCHAR(50) NOT NULL
);
CREATE TABLE REPORTE(
	id_reporte int PRIMARY KEY AUTO_INCREMENT,
	id_user  int NOT NULL,
	cuerpo TEXT(100) NOT NULL,
	FOREIGN KEY (id_user) REFERENCES USUARIO(id_user)
);
CREATE TABLE ReporteEnUsuario(
	id_riu int PRIMARY KEY AUTO_INCREMENT,
	id_user  int NOT NULL,
	id_reporte int NOT NULL,
	FOREIGN KEY (id_user)REFERENCES USUARIO(id_user),
	FOREIGN KEY (id_reporte)REFERENCES REPORTE(id_reporte)
);
INSERT INTO USUARIO (nombre,password) VALUES ('mauricio','contraseña');